// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
#if canImport(AppleProductTypes)
import AppleProductTypes
#endif

let package = Package(
    name: "Sproutly",
    platforms: [
        .iOS("17.0"),
        .macOS("14.0")
    ],
    products: [],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ],
    swiftLanguageModes: [.v6]
)

#if canImport(AppleProductTypes)
package.products.append(
    .iOSApplication(
        name: "Sproutly",
        targets: ["AppModule"],
        bundleIdentifier: "com.jashmadhani.Sproutly",
        teamIdentifier: "FDYHXN3XSH",
        displayVersion: "1.0",
        bundleVersion: "1",
        appIcon: .placeholder(icon: .cloud),
        accentColor: .presetColor(.mint),
        supportedDeviceFamilies: [
            .pad,
            .phone
        ],
        supportedInterfaceOrientations: [
            .portrait,
            .landscapeRight,
            .landscapeLeft,
            .portraitUpsideDown(.when(deviceFamilies: [.pad]))
        ],
        appCategory: .kidsGames
    )
)
#else
package.products.append(.executable(name: "Sproutly", targets: ["AppModule"]))
#endif